# Generated by Django 2.1.1 on 2018-11-19 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='executivebook',
            name='ac_true',
        ),
        migrations.RemoveField(
            model_name='executivebook',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='executivebook',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='executivebook',
            name='location',
        ),
        migrations.RemoveField(
            model_name='executivebook',
            name='us_profile',
        ),
    ]
