# Generated by Django 2.1.1 on 2018-11-19 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0002_auto_20181119_1124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100, null=True)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.TextField(max_length=7, null=True)),
                ('details', models.TextField(max_length=250, null=True)),
                ('income', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('expenses', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookkeeping.Record'),
        ),
        migrations.AddField(
            model_name='executivebook',
            name='accounts',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bookkeeping.Account'),
            preserve_default=False,
        ),
    ]
