# Generated by Django 2.1.1 on 2018-11-19 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0003_auto_20181119_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='list',
        ),
        migrations.AddField(
            model_name='record',
            name='list',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bookkeeping.Account'),
            preserve_default=False,
        ),
    ]
