# Generated by Django 2.1.1 on 2018-11-19 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0005_auto_20181119_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='executivebook',
            name='accounts',
        ),
        migrations.AddField(
            model_name='account',
            name='accounts',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bookkeeping.ExecutiveBook'),
            preserve_default=False,
        ),
    ]
