# Generated by Django 2.1.1 on 2018-11-20 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0007_auto_20181119_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='date',
            field=models.TextField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='expenses',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True),
        ),
    ]
