# Generated by Django 2.1.1 on 2018-11-20 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0009_record_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
