# Generated by Django 2.1.1 on 2018-11-19 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ac_true',
            field=models.BooleanField(default=False),
        ),
    ]
