# Generated by Django 2.1.1 on 2018-11-19 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_profile_ac_true'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='us_profile',
            field=models.TextField(default='../static/admin/img/notifications_white_192x192.png'),
        ),
    ]
